In [1]:
import numpy as np

In [2]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [5]:
arr*arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
arr_2d=arr.reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr_2d**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [9]:
arr_2d/arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr_1d=np.array([1,2,3])
arr_2d*arr_1d

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [11]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [13]:
np.sin(arr_2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [14]:
np.log(arr_2d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [15]:
np.log(np.exp(arr))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
np.cos(arr_2d)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [17]:
np.tan(arr_2d)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [18]:
np.insert(arr,5,10)

array([ 1,  2,  3,  4,  5, 10,  6,  7,  8,  9])

In [19]:
np.delete(arr,7)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [21]:
np.append(arr,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [24]:
np.append(arr_2d,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [25]:
np.where(arr>5,1,arr)

array([1, 2, 3, 4, 5, 1, 1, 1, 1])

In [26]:
np.where(arr>5,1,0)

array([0, 0, 0, 0, 0, 1, 1, 1, 1])

In [27]:
np.where(arr_2d<=5,0,arr_2d)

array([[0, 0, 0],
       [0, 0, 6],
       [7, 8, 9]])

In [29]:
np.insert(arr,5,100)

array([  1,   2,   3,   4,   5, 100,   6,   7,   8,   9])

In [39]:
a = np.array([1,2],[3,4])
b = np.array([5,6])
np.concatenate ((a,b))

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [56]:
import numpy as np
import pandas as pd

In [58]:
labels = ['a', 'b', 'c']
x = [10, 20, 30]


In [59]:
pd.Series(data=x)

0    10
1    20
2    30
dtype: int64

In [60]:
pd.Series(data=x,index=labels)

a    10
b    20
c    30
dtype: int64

In [62]:
pd.Series(x)

0    10
1    20
2    30
dtype: int64

In [63]:
pd.Series(labels)

0    a
1    b
2    c
dtype: object

In [64]:
arr = np.array([2,4,6])

In [65]:
pd.Series(arr)

0    2
1    4
2    6
dtype: int32

In [69]:
d = {'a':'Data','b':'Science','c':30}

In [70]:
pd.Series(d)

a       Data
b    Science
c         30
dtype: object

In [73]:
x=[i for i in range (1,5)]
y=[i for i in range (5,9)]
z=[i for i in range (9,13)]

In [74]:
pd.DataFrame(data=[x,y,z])

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [78]:
pd.DataFrame([x,y,z], 'a b c'.split(), 'w x y z'.split())

w   x   y   z
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [79]:
x_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [81]:
pd.DataFrame(x_list)

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [84]:
from numpy.random import randn

In [85]:
np.random.seed(101)

In [87]:
df = pd.DataFrame(randn(5,4))

In [88]:
df

0         1         2         3
0  0.302665  1.693723 -1.706086 -1.159119
1 -0.134841  0.390528  0.166905  0.184502
2  0.807706  0.072960  0.638787  0.329646
3 -0.497104 -0.754070 -0.943406  0.484752
4 -0.116773  1.901755  0.238127  1.996652

In [89]:
df.loc['new']=[1,2,3,4]
df

0         1         2         3
0    0.302665  1.693723 -1.706086 -1.159119
1   -0.134841  0.390528  0.166905  0.184502
2    0.807706  0.072960  0.638787  0.329646
3   -0.497104 -0.754070 -0.943406  0.484752
4   -0.116773  1.901755  0.238127  1.996652
new  1.000000  2.000000  3.000000  4.000000

In [92]:
df['new']=df[1]+df[2]
df

0         1         2         3       new
0    0.302665  1.693723 -1.706086 -1.159119 -0.012363
1   -0.134841  0.390528  0.166905  0.184502  0.557432
2    0.807706  0.072960  0.638787  0.329646  0.711747
3   -0.497104 -0.754070 -0.943406  0.484752 -1.697476
4   -0.116773  1.901755  0.238127  1.996652  2.139882
new  1.000000  2.000000  3.000000  4.000000  5.000000

In [96]:
df.drop('new',axis=1)

0         1         2         3
0    0.302665  1.693723 -1.706086 -1.159119
1   -0.134841  0.390528  0.166905  0.184502
2    0.807706  0.072960  0.638787  0.329646
3   -0.497104 -0.754070 -0.943406  0.484752
4   -0.116773  1.901755  0.238127  1.996652
new  1.000000  2.000000  3.000000  4.000000

In [101]:
df[4]=df[0]+df[3]
df

0         1         2         3       new         4
0    0.302665  1.693723 -1.706086 -1.159119 -0.012363 -0.856454
1   -0.134841  0.390528  0.166905  0.184502  0.557432  0.049661
2    0.807706  0.072960  0.638787  0.329646  0.711747  1.137352
3   -0.497104 -0.754070 -0.943406  0.484752 -1.697476 -0.012352
4   -0.116773  1.901755  0.238127  1.996652  2.139882  1.879879
new  1.000000  2.000000  3.000000  4.000000  5.000000  5.000000

In [105]:
df.drop('new')

0         1         2         3       new         4
0  0.302665  1.693723 -1.706086 -1.159119 -0.012363 -0.856454
1 -0.134841  0.390528  0.166905  0.184502  0.557432  0.049661
2  0.807706  0.072960  0.638787  0.329646  0.711747  1.137352
3 -0.497104 -0.754070 -0.943406  0.484752 -1.697476 -0.012352
4 -0.116773  1.901755  0.238127  1.996652  2.139882  1.879879

In [106]:
df.reset_index()

index         0         1         2         3       new         4
0     0  0.302665  1.693723 -1.706086 -1.159119 -0.012363 -0.856454
1     1 -0.134841  0.390528  0.166905  0.184502  0.557432  0.049661
2     2  0.807706  0.072960  0.638787  0.329646  0.711747  1.137352
3     3 -0.497104 -0.754070 -0.943406  0.484752 -1.697476 -0.012352
4     4 -0.116773  1.901755  0.238127  1.996652  2.139882  1.879879
5   new  1.000000  2.000000  3.000000  4.000000  5.000000  5.000000

In [107]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [110]:
z = 'JKT BDG BGR BKS TNG CRB'.split()
z

['JKT', 'BDG', 'BGR', 'BKS', 'TNG', 'CRB']

In [111]:
df['Kota'] = z
df.set_index('Kota')

0         1         2         3       new         4
Kota                                                            
JKT   0.302665  1.693723 -1.706086 -1.159119 -0.012363 -0.856454
BDG  -0.134841  0.390528  0.166905  0.184502  0.557432  0.049661
BGR   0.807706  0.072960  0.638787  0.329646  0.711747  1.137352
BKS  -0.497104 -0.754070 -0.943406  0.484752 -1.697476 -0.012352
TNG  -0.116773  1.901755  0.238127  1.996652  2.139882  1.879879
CRB   1.000000  2.000000  3.000000  4.000000  5.000000  5.000000

In [112]:
df

0         1         2         3       new         4 Kota
0    0.302665  1.693723 -1.706086 -1.159119 -0.012363 -0.856454  JKT
1   -0.134841  0.390528  0.166905  0.184502  0.557432  0.049661  BDG
2    0.807706  0.072960  0.638787  0.329646  0.711747  1.137352  BGR
3   -0.497104 -0.754070 -0.943406  0.484752 -1.697476 -0.012352  BKS
4   -0.116773  1.901755  0.238127  1.996652  2.139882  1.879879  TNG
new  1.000000  2.000000  3.000000  4.000000  5.000000  5.000000  CRB

In [113]:
df.set_index('Kota', inplace=True)

In [114]:
df

0         1         2         3       new         4
Kota                                                            
JKT   0.302665  1.693723 -1.706086 -1.159119 -0.012363 -0.856454
BDG  -0.134841  0.390528  0.166905  0.184502  0.557432  0.049661
BGR   0.807706  0.072960  0.638787  0.329646  0.711747  1.137352
BKS  -0.497104 -0.754070 -0.943406  0.484752 -1.697476 -0.012352
TNG  -0.116773  1.901755  0.238127  1.996652  2.139882  1.879879
CRB   1.000000  2.000000  3.000000  4.000000  5.000000  5.000000